export const FEEDBACK_ACTION ={
    FETCH_USER:'FEEDBACK_FETCH_USER',
    REQUEST_START:'REQUEST_START',
    SET_USER:'FETCH_SET_USER',
    GET: 'FETCH_FEEDBACK',
    SET: 'SET_FEEDBACK',
    POST: 'POST_FEEDBACK',
    ADD:'ADD_FEEDBACK',
    DELETE: 'DELETE_FEEDBACK'
}

