export const USER_ACTIONS = {
  FETCH_USER: 'FETCH_USER',
  SET_USER: 'SET_USER_ACTION',
  UNSET_USER: 'UNSET_USER_ACTION',
  REQUEST_START: 'REQUEST_START_USER_ACTION',
  REQUEST_DONE: 'REQUEST_DONE_USER_ACTION',
  LOGOUT: 'LOGOUT',
  USER_FETCH_FAILED: 'USER_FETCH_FAILED',
  /////First Call
  ADD_FEEDBACK:'USER_ADD_FEEDBACK',
  ADD_NEWINFO:'USER_ACTION_ADD_NEWINFO',
  ADD_EDIT:'USER_ACTION_ADD_EDIT',
  ///Second call
  SET_UPDATE: 'SET_UPDATE',
};


